name: 'Build and publish to dockerhub'
description: 'Build and publish to dockerhub'
inputs:
  DOCKERHUB_USERNAME:
    description: 'DOCKERHUB_USERNAME'
    required: true
  DOCKERHUB_PASSWORD:
    description: 'DOCKERHUB_PASSWORD'
    required: true
  tag:
    description: 'Tag name'
    required: true
  arg:
    description: 'Build Arg'
    required: false
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
    default: ./Dockerfile
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_PASSWORD }}
    - name: Build image
      uses: docker/build-push-action@v2.5.0
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        tags: imiobe/libreoffice:${{ inputs.tag }}
        platforms: linux/amd64
        pull: true
        push: true
        build-args: LO_PPA=${{ inputs.arg }}
    - name: Show version
      shell: bash
      run: |
        docker pull -q imiobe/libreoffice:${{ inputs.tag }}
        docker run imiobe/libreoffice:${{ inputs.tag }} soffice --version
    - name: Tag version
      shell: bash
      run: |
        docker tag imiobe/libreoffice:${{ inputs.tag }} imiobe/libreoffice:"$(docker run imiobe/libreoffice:${{ inputs.tag }} soffice --version | cut -d ' ' -f 2 | cut -d '.' -f 1-2)"
        docker push imiobe/libreoffice:"$(docker run imiobe/libreoffice:${{ inputs.tag }} soffice --version | cut -d ' ' -f 2 | cut -d '.' -f 1-2)"
#    - name: Show fonts
#      shell: bash
#      run: |
#        docker run imiobe/libreoffice:${{ inputs.tag }} fc-list : family | sort | uniq
