name: Update images
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * *' # Weekly on Sundays at 03:00
jobs:
  ubuntu_20_04_still:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 6-4
        uses: docker/build-push-action@v2.5.0
        with:
          file: still/Dockerfile
          tags: imiobe/libreoffice:still
          pull: true
          push: true

  ubuntu_20_04_fresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: 6-4
        uses: docker/build-push-action@v2.5.0
        with:
          file: fresh/Dockerfile
          tags: imiobe/libreoffice:fresh
          pull: true
          push: true
