name: Publish to Dockerhub
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 3 * * 1' # Weekly on Mondays at 03:00
jobs:
  ubuntu_22_04_lo_default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.COMMON_HARBOR_USERNAME }}
          password: ${{ secrets.COMMON_HARBOR_PASSWORD }}
      - name: Build image
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./Dockerfile-default
          tags: imiobe/libreoffice:default
          platforms: linux/amd64
          pull: true
          push: true
          build-args: LO_PPA=default
      - name: Show version
        shell: bash
        run: |
          docker pull -q imiobe/libreoffice:default
          docker run imiobe/libreoffice:default soffice --version
      - name: Tag version
        shell: bash
        run: |
          docker tag imiobe/libreoffice:default imiobe/libreoffice:"$(docker run imiobe/libreoffice:default soffice --version | cut -d ' ' -f 2 | cut -d '.' -f 1-2)"
          docker push imiobe/libreoffice:"$(docker run imiobe/libreoffice:default soffice --version | cut -d ' ' -f 2 | cut -d '.' -f 1-2)"
